### ISSUE TITLE
Looking for example on how to conduct graphcut on using push relabel?

### ISSUE THREAD

**Issue by merlinarer** [gunrock/gunrock#1038]
I'm currently working on a paper that requires using the Graph Cut algorithm on GPU. I was wondering if anyone could point me towards some example implementations that demonstrate how to use push relabel in this repo to conduct Graph Cut effectively. 
Thanks in advance for your assistance!

**Comment by neoblizz** [comment]
Hi @merlinarer, I have limited knowledge about push relabel, but I believe you are talking about our MaxFlow implementation available here: https://github.com/gunrock/gunrock/tree/dev/examples/mf and documented here: https://gunrock.github.io/docs/#/hive/hive_sparse_graph_trend_filtering. MaxFlow from our study was not performant (in fact, CPU implementation was better than ours) because it is a challenging algorithm to make parallel.

Additionally, this work exists in an older version of Gunrock (dev and master branch) and not in our new, simpler APIs (develop and main). If you'd like to port this or implement it within our new API, I am happy to provide insights on how the library works, but beyond that I do not have the expertise around Graph Cut or MaxFlow to really give you any guidance.

If you have sequential C++ implementations, that can help derive this conversation further.
