### ISSUE TITLE
Block Mapped Thread Degrees Exclusive Sum Problem

### ISSUE THREAD

**Issue by kaanolgu** [gunrock/gunrock#1071]
Hi, 
I am having a bit tough time understanding the need of exclusive sum in the block_mapped.hxx file here:

https://github.com/gunrock/gunrock/blob/5b16ff134ab9eb98b1019e3bd6909b5c8dbd7c0f/include/gunrock/framework/operators/advance/block_mapped.hxx#L84C1-L87C19

For example, let's assume  a block has 4 threads and each thread's th_deg holds:

th_deg[0] = 2 (Thread 0)
th_deg[1] = 3 (Thread 1)
th_deg[2] = 5 (Thread 2)
th_deg[3] = 1 (Thread 3)
After the exclusive prefix sum:

th_deg[0] = 0 (initially 0 for exclusive sum)
th_deg[1] = 2 (sum of previous th_deg[0])
th_deg[2] = 5 (sum of previous th_deg[0] + th_deg[1])
th_deg[3] = 10 (sum of previous th_deg[0] + th_deg[1] + th_deg[2])
aggregate_degree_per_block will hold:

aggregate_degree_per_block = 2 + 3 + 5 + 1 = 11

But what I found is `th_deg` is defined as:
 https://github.com/gunrock/gunrock/blob/5b16ff134ab9eb98b1019e3bd6909b5c8dbd7c0f/include/gunrock/framework/operators/advance/block_mapped.hxx#L65C1-L65C35

where `ITEMS_PER_THREAD`  is equal to 1. So actually isn't this `ExclusiveSum` just is equal to :
```
aggregate_degree_per_block = th_deg[0]; 
```

**Comment by neoblizz** [comment]
I am not sure I understand the last bit:

> where `ITEMS_PER_THREAD` is equal to 1. So actually isn't this `ExclusiveSum` just is equal to :
> 
> ```
> aggregate_degree_per_block = th_deg[0]; 
> ```

`aggregate_degree_per_block` is populated for the entire block, since its a block level scan. So, you'd get `aggregate_degree_per_block = 11` in all of the threads. `th_deg` is a register, so its scope is thread-only. Each thread sees its "own" `th_deg`, so if you did:

``` 
 aggregate_degree_per_block = th_deg[0];
```

Each thread will have a different `aggregate_degree_per_block`, which is incorrect.

What `th_deg` is doing is its taking `THREADS_PER_BLOCK` number of vertices, where each thread is only configuring (finding the degree of) one vertex, so `ITEMS_PER_THREAD=1`. Once the scan is computed, what you really learn is how much work the THREAD BLOCK has to do (not individual threads).

Lets say in your example, by the time you get to the for-loop that is actually processing the work, each thread knows how many total edges to process (11), and what source vertex that edge corresponds to (using a binary search into the exc scan array).

https://github.com/gunrock/gunrock/blob/5b16ff134ab9eb98b1019e3bd6909b5c8dbd7c0f/include/gunrock/framework/operators/advance/block_mapped.hxx#L112-L116

The for loop shows that `i` is the thread in the block, its processing one edge and then stepping by the dimension of the block to process the next edge not processed by any other thread in the block. 
However, to relate that edge to the source/neighbor it belongs to, you use a binary search over the exclusive sum array now stored in shared memory to figure out which offset belongs to, i.e. getting the original source vertex for that edge:  https://github.com/gunrock/gunrock/blob/5b16ff134ab9eb98b1019e3bd6909b5c8dbd7c0f/include/gunrock/framework/operators/advance/block_mapped.hxx#L122-L123

**Comment by kaanolgu** [comment]
Thank you for detailed explanation @neoblizz it clears all the confusion I had
