### ISSUE TITLE
Reduce compilation time by reorganize template parameters

### ISSUE THREAD

**Issue by sgpyc** [gunrock/gunrock#110]
The compilation time is too long, should downgrade some template parameters to just run time parameters. Suggest only make something a template parameter if it either 1) determines data type, or 2) crosses CPU-GPU boundary and have performance impact. Flags that only affect CPU control flow should not be template parameters (e.g. DEBUG, SIZE_CHECK). One extra template parameter doubles the compilation time.

**Comment by yzhwang** [comment]
Agree. Here is my thought:
1) VertexID, SizeT can be replaced with long/long long and unsigned long separately. Only Value should be preserved since it varies according to different algorithms. Not sure if this will affect the 64-bit setting.
2) LOAD_PER_TILE and LOAD_VEC_SIZE could be removed once we find a better way to do  traversal-mode=1 (Now it loads data from global mem to local mem and uses template-based tail recursion to loop unroll) I will open another issue on trying different mem access/organization strategy for traversal-mode=1.
3) All flags could be replaced with parameters. Actually, we might want to start the design of sending in a configuration structure handle some time. This also deserves another issue.

**Comment by jowens** [comment]
make *sure* that if you remove those datatypes (`VertexID`, `SizeT`) from the templates, they're at least made typedefs somewhere. Honestly, though, will that save any time? If you only instantiate those datatypes with one instance each in practice, the template cost is free. It's only when we have multiple choices for any particular template argument that it costs us; but then that's exactly what templates are good for. The enormous benefit of having everything wrapped into the template is that we design for an arbitrary data type. That's a big benefit. If we downgrade a template argument to something static, and then we want to change it / make it work for multiple datatypes later, that often results in a bunch of work since we've assumed stuff about our static choice. Anyway, this is just a caution that we make good decisions and don't overly prioritize compile time over other considerations.

**Comment by yzhwang** [comment]
After looking at some of the code, I assume that a large part of the compilation time is caused by the latter two items. Even the last item, which uses flag as template parameter, will only go into one branch in a multiple-branch path. For the first item, I agree it does not contribute much to the compilation time, the only difference between VertexId and SizeT is SizeT is actually just size_t, VertexId can be negative for some reserved flags showing invalid status. Maybe we can add an enumerator of vertex status normal/invalid so that we can merge VertexId and SizeT into size_t (or unsigned long). So I think the key to the compilation time is the 2nd item: LOAD_PER_TILE and LOAD_VEC_SIZE as template parameters.

**Comment by sgpyc** [comment]
datatypes (VertexId, SizeT, Value) are being kept in the template, and they can be 32 or 64 bits depending on command line parameters (like here https://github.com/gunrock/gunrock/blob/dev/tests/bfs/test_bfs.cu#L815 ). However, I guess normally these selections should be OFF for now.

Things that really matter is 2) and 3) mentioned by @yzhwang . I'm doing 3), and compilation time for bfs reduced to 1/8 by downgrading INSTRUMENT, DEBUG, SIZE_CHECK to variables inside Enactor class. For 2), I guess can change that into a normal for loop style with unrollable loop conditions.

**Comment by sgpyc** [comment]
I think this issue had been addressed by commit caa203b
