### ISSUE TITLE
Compile error 

### ISSUE THREAD

**Issue by fvella** [gunrock/gunrock#13]
error: no instance of function template "gunrock::oprtr::advance::LaunchKernel" matches the argument list
argument types are: (int *, gunrock::app::EnactorStats, gunrock::app::FrontierAttribute, gunrock::app::bfs::BFSProblem::DataSlice *, VertexId *, __nv_bool *, __nv_bool *, unsigned int *, int *, int *, VertexId *, int *, int *, int *, SizeT *, VertexId *, int, int, gunrock::util::CtaWorkProgressLifetime, mgpu::CudaContext, gunrock::oprtr::advance::TYPE)
detected during:
instantiation of "cudaError_t gunrock::app::bfs::BFSEnactor::EnactBFS(mgpu::CudaContext &, BFSProblem *, BFSProblem::VertexId, int) [with INSTRUMENT=true, AdvanceKernelPolicy=gunrock::oprtr::advance::KernelPolicy, 300, true, 8, 10, 8, 4096, 1, 0, 5, 32, 512, 7, LB>, FilterKernelPolicy=gunrock::oprtr::filter::KernelPolicy, 300, true, 0, true, 8, 8, 1, 0, 5, 5, 8>, BFSProblem=gunrock::app::bfs::BFSProblem]"
(495): here
instantiation of "cudaError_t gunrock::app::bfs::BFSEnactor::Enact(mgpu::CudaContext &, BFSProblem *, BFSProblem::VertexId, int, int) [with INSTRUMENT=true, BFSProblem=gunrock::app::bfs::BFSProblem]"

I am using:
CUDA 6.5,
GCC / G++ 4.4.7
CENTOS 6.4
Boost version: 1.57.0
cub 1.3.2
modernGPU

**Comment by yzhwang** [comment]
Hi, can you try to pull the latest version: https://github.com/gunrock/gunrock/commit/b588f8920bc2424eeeab0d778ab4da4b15d9b2c1
I think I have fixed this.

**Comment by yzhwang** [comment]
So we are currently checking the interface inconsistency for other graph primitives. We have recently added the neighborhood gather reduce feature. That should be the problem which caused the issue. Will let you know when we fix this.

**Comment by ydwu** [comment]
@fvella  The cmake list out-of-date, will fix this later.

**Comment by fvella** [comment]
Thanks guys!
From scratch installation, after run make:
"/usr/src/gunrock/gunrock-master/gunrock/util/sort_utils.cuh:21:23: error: cub/cub.cuh: No such file or directory
CMake Error at gunrock_generated_topk_app.cu.o.cmake:206 (message):
  Error generating
  /usr/src/gunrock/gunrock/CMakeFiles/gunrock.dir/app/topk/./gunrock_generated_topk_app.cu.o

make[2]: *** [gunrock/CMakeFiles/gunrock.dir/app/topk/./gunrock_generated_topk_app.cu.o] Error 1
make[1]: *** [gunrock/CMakeFiles/gunrock.dir/all] Error 2
make: *** [all] Error 2
"
Note
I have extracted  cub and moderngpu into "external" directory.

**Comment by ydwu** [comment]
@fvella You should be able to compile now, currently we breadth_first_search, direction-optimizing-bfs, minimum_spanning_tree, connected_component, hyperlink_induced_topic_search and single_source_shortest_path in the CMakeList. Several other primitives are have some issues that might due to the recent interface change, will add those once we done tests.

**Comment by fvella** [comment]
I have downloaded the last release, but I have the same problem.
I have copied cub e moderngpu onto externals.
Cmake works!
run make
Here's the output:
In file included from /usr/src/gunrock/gunrock-master/gunrock/app/topk/topk_enactor.cuh:19,
                 from /usr/src/gunrock/gunrock-master/gunrock/app/topk/topk_app.cu:21:
/usr/src/gunrock/gunrock-master/gunrock/util/sort_utils.cuh:21:23: error: cub/cub.cuh: No such file or directory
CMake Error at gunrock_generated_topk_app.cu.o.cmake:206 (message):
  Error generating
  /usr/src/gunrock/gunrock/CMakeFiles/gunrock.dir/app/topk/./gunrock_generated_topk_app.cu.o


make[2]: *** [gunrock/CMakeFiles/gunrock.dir/app/topk/./gunrock_generated_topk_app.cu.o] Error 1
make[1]: *** [gunrock/CMakeFiles/gunrock.dir/all] Error 2
make: *** [all] Error 2


Do I have to customize the include files into utilities ?

**Comment by ydwu** [comment]
You actually do not need to copy those dependencies manually you can follow these steps:
1. git clone https://github.com/gunrock/gunrock
2. cd gunrock/
$ git checkout 7a43bc8da (simply because I tested this version yesterday.)
3. git submodule init
4. git submodule update (after step 3 and 4, you should have the cub and moderengpu in the externals)
5. cd ../ && mkdir build (if you want to have a build path separately)
6. cd build/
7. cmake ../gunrock -i (Y - enable advance settings, and change the first one Boost_INCLUDE_DIR to your Boost path and skip the rest)
If no error, should be something like this:
build$ cmake ../gunrock/
-- Boost version: 1.53.0
-- Configuring done
-- Generating done
-- Build files have been written to: ...
You can then make or make -j8 and the binaries will in the bin/
Is this work for you?

**Comment by fvella** [comment]
Works!
**Minor** Please check run.sh samples (i.e. BFS). Maybe the paths into the script are not correct.

**Comment by ydwu** [comment]
Thanks for your feedback, we will updates those scripts.

**Comment by fvella** [comment]
Hi guys,
Does bc work in current branch ?
