### ISSUE TITLE
PageRank radixsort error on directed graphs.

### ISSUE THREAD

**Issue by yzhwang** [gunrock/gunrock#14]
[../../gunrock/app/pr/pr_enactor.cuh, 466] cub::DeviceRadixSort::SortPairsDescending failed (CUDA error 9: invalid configuration argument)
[test_pr.cu, 339] pr Problem Enact Failed (CUDA error 9: invalid configuration argument)

**Comment by ydwu** [comment]
This issue is not related to cub sort actually. Some invalid reads are reported by memcheck.

**Comment by sashkiani** [comment]
@ydwu Could you fix this? On a different topic, I'm having exactly the same error in my code using CUB.  
I just realized that whenever I include thrust/sort.h in my code as well, I get this error. By not including that, everything looks fine and works perfectly.

**Comment by ydwu** [comment]
Hi @sashkiani, this problem was originally observed running `bin/pagerank market directed_graph.mtx`, but now I actually cannot reproduce the same issue when I switch back using `CUB's sort` (for safety I changed it to `mgpu::sort` in current `master` branch). Changing [pr_enactor.cuh L393](https://github.com/gunrock/gunrock/blob/master/gunrock/app/pr/pr_enactor.cuh#L393) back to:

    util::CUBRadixSort<Value, VertexId>(
            false, graph_slice->nodes,
            problem->data_slices[0]->d_rank_curr,
            problem->data_slices[0]->d_node_ids);


Running  `bin/pagerank` without problem for all datasets we have. I guess it was fixed somehow near commit e7dbca58e7ad43ab23be9da1ab1b1849d9cee42a but not sure why.

Wired enough though, I did more tests and observe that in [gunrock simple interface test](https://github.com/gunrock/gunrock/blob/master/shared_lib_tests/simple_interface_test.c) if I run BFS and/or BC before calling PageRank, this error will occur, but other two primitives SSSP and CC does not have any impact. However, if I comment out [L29 and L30](https://github.com/gunrock/gunrock/blob/master/shared_lib_tests/simple_interface_test.c#L29), this error disappear. In my case, I did't include any other library such as `thrust/sort.h` though, can you find any link? 

Also I recall that "CUDA error 9" is possibly because of [CUDA launch kernel parameter settings](http://stackoverflow.com/questions/16125389/invalid-configuration-argument-error-for-the-call-of-cuda-kernel). Maybe you can try to check that.
