### ISSUE TITLE
Random Spanning Tree Question/Feature

### ISSUE THREAD

**Issue by felipegb94** [gunrock/gunrock#150]
Hi,

Does gunrock have a forum for questions? 

I skimmed through the functions in the toolbox looking for a random spanning tree (RST) function but was unable to find any. Do you have an implementation of it? Or I'm I right in assuming that it is not a feature (yet?). Assuming RST is not a feature in gunrock, how hard would it be to implement it using the currently existing data structures and functions in the toolbox? Do you have any pointers to what parts of the code and examples to look at if I would like to implement it? 

Here is the boost [RST function](http://www.boost.org/doc/libs/1_60_0/libs/graph/doc/random_spanning_tree.html)

Thanks!

**Comment by yzhwang** [comment]
Hi @felipegb94 We do not have a forum, but I think you are doing the exactly right thing: putting questions and feature requests in issues.
As for RST. We currently do not support this primitive. And since we don't have a good parallel random walk implementation on the GPU too, it is gonna be hard to present the algorithm using Gunrock. We do have a MST implementation but it only works on single-GPU and a single connected component. That said, if you are interested in using Gunrock for RST and want any kind of support or help, please let us know.

**Comment by jowens** [comment]
Hi @felipegb94. We discussed this problem in group meeting yesterday. Can you comment from the point of view of your application what you expect in terms of "random"? What are you prioritizing when you randomize? If you generated a zillion random trees, you would expect a uniform random distribution of ... what? (For instance, you might say that every edge connected to vertex v should have an equal probability of being in the tree.) Any algorithm that we/you pick is probably going to have particular biases that you might or might not care about; we need to know what those biases are. 

One possibility for implementation, for instance, is to choose a random vertex and do a BFS from that vertex, and as we traverse edges to do the BFS, only "mark" edges that connect the current MST to a vertex that is not in the current MST. This should generate a MST, but should we randomly select start vertices, is that enough for you? And the implementation would probably be biased in favor of connections from vertices with lower vertex IDs, because we probably will traverse from those vertices within a single "advance" operator before we traverse from vertices with higher vertex IDs. Does that matter? Anyway, if these biases are acceptable for you, I think it would be fairly straightforward to implement; it would require a non-idempotent BFS; and I'm certainly not the person to give low-level implementation details. :)
