### ISSUE TITLE
CUDA version requirement

### ISSUE THREAD

**Issue by smsaladi** [gunrock/gunrock#155]
I would like to run gunrock on a GPU resource, but the latest CUDA installed is 6.5 on one and 7.0 on another. Unfortunately, upgrading the CUDA toolkit on either resource doesn't seem to be possible at the moment. Does the 7.5 requirement comes from some specific feature requirement, or is it just what has been tested with?

I know the following is written on the README, but I thought I'd still ask for clarification.

> This release (0.3) has been tested on Linux Mint 15 (64-bit), Ubuntu 12.04, 14.04 and 15.10 with CUDA 7.5 installed. We expect Gunrock to build and run correctly on other 64-bit and 32-bit Linux distributions, Mac OS, and Windows.

> Requirements

> CUDA version 7.5 (or greater) and compute capability 3.0 (or greater) is required.

> Several graph primitives' CPU validation code uses Boost Graph Library. We are also using Boost Spirit, filesystem, and timer in our utility code. A boost version > 1.56.0 is required (1.58.0 is recommended).

**Comment by jowens** [comment]
We switched to 7.5 when we found a compiler bug in 7.0 that got fixed in 7.5. So there is at least part of Gunrock that won't compile correctly if you use something < 7.5. That might be OK with you, in which case you have our blessing to use 7.0. I believe at least some development was done in 6.5, but at this point we use C++11 features and that requires at least 7.0 IIRC.

The README requirements are AFAIK correct.
