### ISSUE TITLE
runtime variance issue (Jayadharini Jaiganesh)

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#160]
Placeholder for this issue to make sure we don't lose it.

**Comment by yzhwang** [comment]
The runtime fluctuations are caused by iteration variation, which can be as large as 5 for weblink datasets. The reason for iteration variation is because of the way Gunrock relax edges in parallel:
https://github.com/gunrock/gunrock/blob/dev_debug/gunrock/app/sssp/sssp_functor.cuh#L76
For example, suppose we have 4 nodes with current distance to source all set to 1, they all have a common child node, which will be discovered in the next iteration by visiting each of the 4 node's neighbor list. The edges connect these 4 nodes and the common child node have edge weight 1,2,3,4 separately. Now when we expand the neighbor list, any order can happen, if we happen to relax the edge according to the ascending order of edge weight, then the common child node's distance will be updated to 1+1=2 during the first parent, so it will only appear once in the input frontier of the next iteration, however, if we happen to relax the edge according to the descending order of edge weight, then the common child node will appear 4 times in the next iteration.

In our master branch and the release version for PPoPP'16, we have priority queue, which compact and filter the output frontier into two level arrays, and the valid array will eliminate the redundant:
https://github.com/gunrock/gunrock/blob/master/gunrock/priority_queue/kernel.cuh#L178

That said, with priority queue, the output frontier of each iteration will also change according to different settings of delta-factor.

In our multi-GPU implementation, we disabled priority queue and also used a very simple filter to only filter out nodes whose distance value don't change during the relax phase. But for redundancy as I mentioned above, it doesn't get rid of all of them.

The SSSP implementation of Andrew Davidson uses the filter in priority queue to eliminate the redundancy so it can get rid of all the redundant nodes.
