### ISSUE TITLE
Create new run scripts

### ISSUE THREAD

**Issue by yzhwang** [gunrock/gunrock#205]
We need to organize the current scripts under each test folder into the following categories:
1) PPoPP test (to recreate our PPoPP results): I think we already have them as ppopp_test.sh. I assume with the new release the results would have some changes though.
2) mGPU test (to recreate our multi-GPU results): Currently there are run.sh, run_real.sh, and run_rmat.sh. I'm not sure if we need to merge these three into one? @sgpyc need your input here.
3) Results on Pascal architecture: @sgpyc did you use a different set of command lines or did you use the same scripts as those mGPU tests?

@jowens I hope this is what you meant on slack channel.

**Comment by jowens** [comment]
Yes, this is what I meant on slack channel.

I'd personally do these in Python, but that's an easy switch if we want from sh. I don't really care how they're organized; having a hierarchy is perfectly fine ("here's a set of quick 1GPU tests, here's a full set of 1GPU tests", etc.). I do care that we can regenerate any result we published from them (in particular the PPoPP results), and that it's easy to add a new dataset if we want. It is desirable if they're configurable in terms of where the data resides, since it's different on mario/luigi compared to your local workstation or laptop, but that's pretty easy.

I prioritize 1GPU more than mGPU at this point.

I want to get JSON into the repo. @sgpyc maybe you can illuminate us with your current concern there (I think you have way more JSON than you think is reasonable to drop into the repo and need some way to filter it down ... ?).

**Comment by sgpyc** [comment]
run.sh and run_real.sh are both for fixed datasets, but with different selections.
run.sh selects smaller datasets, and has fewer parameter selection. If you want a quick run, this should be it.
run_real.sh selects larger datasets, and tests all possible parameter combinations. It takes hours or days to run. If you want to do performance analysis or fully systematic test, this is the one.
run_rmat.sh is the sibling of run_real.sh, but on generated datasets.
There may be a run_scale.sh for (DO)BFS and PR, which is used specifically for weak / strong scaling test.

There is a DATADIR value in the .sh scripts, which points to the data directory.

**Comment by neoblizz** [comment]
@sgpyc should we merge all these into one file and have a command option to run the tests, default being the run.sh?

**Comment by jowens** [comment]
@sgpyc can you address the issue with putting the runs you've already done into the repo? (Were those mGPU runs only or 1GPU also?)

**Comment by sgpyc** [comment]
My concern about the JSON is this: how to select JSON files from duplicated ones.

Background: multiple runs of the same primitive with the same parameters on the same machine have been performed (for the nature of testing / debugging), so duplicated .json files have been created (with different time stamp). The actual output are also written into .txt files, which will be overwritten if extractly the same experiment is carried out (same primitive, dataset, parameter, hardware, software environment).

What I want: only the latest JSON, for the ones with same {primitive, dataset, parameter, hardware, software}.
What maybe useful: only the latest one has a corresponding .txt file, with a mostly identical time stamp (in the linux file attribute).
Alternatives: 1) upload them all. There're many of them, and maybe noisy for post analysis.
 2) manual selection. Plausible, but not practical. there are ~13k records all together

**Comment by jowens** [comment]
If we *only* stored the most recent ones for any combination of {prim, ds, param, hw, sw}, would that work? I think I can write a python script to do this in under an hour.

**Comment by jowens** [comment]
if so, just tar/gzip them up and I'll take care of it.

**Comment by sgpyc** [comment]
er... merging is possible, but that may create a run.sh that's hundreds of lines long, with sections activated by huge if-then-else statement. If we are expecting anyone else to look into that, it may not be easy. @neoblizz can have a look at scripts under tests/bfs, and see what's the best.

**Comment by sgpyc** [comment]
@jowens okey, I'm compressing them.

**Comment by jowens** [comment]
@neoblizz feel free to port them to python :) e.g., https://github.com/gunrock/io/blob/master/scripts/gunrock_all.py

**Comment by sgpyc** [comment]
er... the executables made by the cmake-make method may not have all the parameters / optimizations available, because of the interface barrier.

**Comment by jowens** [comment]
Is it fair just to collapse all entries that have the same command line + hardware down to one entry (the latest one)?

**Comment by sgpyc** [comment]
@jowens If just want to keep the latest results, then yes

**Comment by sgpyc** [comment]
@jowens uploaded the results on mario. If that works, I will push more from the cluster (more mGPU results) and my home machine (more 1GPU results by GTX 1070)

**Comment by neoblizz** [comment]
@sgpyc did you write the .sh tests only for bfs?

**Comment by sgpyc** [comment]
BFS, SSSP, BC, CC, and PR each has its own .sh scripts under test/xxx

**Comment by neoblizz** [comment]
Got it, thanks!

**Comment by jowens** [comment]
I do not like this file:

`BFS.ubuntu14.04_k40cx3.tar.gz ubuntu14.04_k40cx3/BFS_soc-orkut_Wed Sep 14 132619 2016.json`

It appears to have zero length.

Gonna special case that.

**Comment by jowens** [comment]
some of these have `"gunrock_version" : "GUNROCKVERSION"`, this seems bad.

**Comment by sgpyc** [comment]
Just checked the records, the two datasets (soc-orkut, and soc-sinaweibo) with parameter --undirected --idempotence --mark-preds --64bit-SizeT, were on the spot that I killed the execution of the run script. I think they can be ignored

**Comment by jowens** [comment]
@sgpyc does 923 single-GPU runs look about right?

**Comment by sgpyc** [comment]
GUNROCKVERSION is defined by CMakelist.txt, and tests/xxx/test_xxx.cu don't have that.
I think next up we need to integrate gunrock/app/xxx/xxx_app.cu and tests/xxx/test_xxx.cu, so they have the same functionalities, and only one set of executable created by the cmake-make routine.

**Comment by jowens** [comment]
👍

**Comment by jowens** [comment]
@sgpyc there are only {BC, CC, PR} results for 1 GPU? No BFS?

**Comment by sgpyc** [comment]
@jowens 1GPU BFS result is not on mario, I verified 1GPU BFS on another machine, and can upload it latter today.
SSSP is still running, now I only have 1GPU results and most for dual-GPUs

**Comment by jowens** [comment]
OK. All I'm looking at right now is 1GPU, so please upload (only) the 1GPU SSSP and BFS when you can. Does 923 runs seem right for {BC, CC, PR}? (Seems like many benchmark/primitive combos have 10 options: 5 traversal modes and 32/64b.)

**Comment by jowens** [comment]
```
$ ls -l new/* | grep SSSP | wc -l
720
$ ls -l new/* | grep BC | wc -l
150
$ ls -l new/* | grep CC | wc -l
300
$ ls -l new/* | grep Page | wc -l
473
```

**Comment by sgpyc** [comment]
Below are the parameter combinations for all the runs
BFS : {default, undirected} x {normal, idempotence} x {skip_pred, mark_pred} x {top_down, do}
          x {32bit-VertexId, 64bit-SizeT, 64bit-VertexId} x {DEF, LB, TWC, LB_CULL}
          = 2880 runs for 1GPU
SSSP : {default, undirected} x {skip_pred, mark_pred} x {32bit-VertexId, 64bit-SizeT} 
         x {DEF, LB, TWC, LB_CULL, LB_LIGHT, LB_LIGHT_CULL}
         = 720 runs for 1GPU
BC : {32bit_SizeT, 64bit_SizeT} x {DEF, LB, LB_CULL, LB_LIGHT, LB_LIGHT_CULL}
         = 150 runs for 1GPU
CC : {default, undirected} x {32bit_SizeT, 64bit_SizeT} x {DEF, LB, TWC, LB_LIGHT, ALL_EDGES}
         = 300 runs for 1GPU
PR : {5 different PR modes} x {32bit-VertexId, 64bit-SizeT, 64bit-VertexId} x {DEF, LB, LB_LIGHT}
         = 675 runs for 1GPU

so {BC, CC, PR} should have 1125 runs for 1GPU. some of them may run out of memory. I think PR only has 473 runs for 1GPU, because perviously TWC is included in the script, and it forced me to manually kill the script multiple times and not all the runs were completed

**Comment by jowens** [comment]
OK my script looks perfectly cromulent, thanks.
