### ISSUE TITLE
MST not in pre-release?

### ISSUE THREAD

**Issue by jayavanth** [gunrock/gunrock#222]
I don't see MST in pre-release. Is it completely removed? Also, MST is breaking in dev (similar to [this issue](https://github.com/gunrock/gunrock/issues/123))

**Comment by sgpyc** [comment]
Hi, MST is not in pre-release branch, partially because of the memory issue you have seen.
It's in dev branch, and should be working when memory is sufficient.
We would like to improve it after the 0.4 release, and graduate it after going though the same level of testing we have done on primitives in the pre-release branch.
