### ISSUE TITLE
Use variable already on the GPU.

### ISSUE THREAD

**Issue by GMolini** [gunrock/gunrock#235]
Is there a way to pass or assign a variable to gunrock that ahs already been allocated in the GPU? Imagine  I want to do the BFS and the sssp on the same graph, do I always need to copy two times the data?

**Comment by yzhwang** [comment]
Thank you @gumlym We have been thinking of adding this feature for a while. Currently Gunrock does not support inter-problem shared device pointer. But with our current Array1D and Array2D wrapper on top of raw device data. I think with very small changes we can expose such interface to users.

@sgpyc So the plan is to support sending in an already allocated/initialized external device pointer (at the user's own risk) to our problem class initialization function. Also I'm thinking of adding a sharable attribute to our Array class so that device pointers can be shared across different primitives. Of course ideally we should manage the device memory ourselves, for example, have all the device memory allocated in a pool and other classes only refer to the pointers that point to addresses in this pool.

@sgpyc Feel free to decide what you want to do or assign this to other students in the group. I just think this is a very reasonable request and it would be nice if Gunrock will support this in the future. Thank you!

**Comment by sgpyc** [comment]
The actual code that move the CSR from CPU to GPU is from https://github.com/gunrock/gunrock/blob/master/gunrock/app/problem_base.cuh#L223 to https://github.com/gunrock/gunrock/blob/master/gunrock/app/problem_base.cuh#L240 .

If there is only one GPU involved, and the CSR content do not need to be touched on CPU, then this should work:
1. set the raw pointers of row_offsets and column_indices in the CSR data structure to device pointers, pointing to content existing on the GPU;
2. add a third parameter `util::DEVICE` to the SetPointer() calls at line 223 and line 224, to tell the source pointers are device pointers. SetPointer()'s signature is here https://github.com/gunrock/gunrock/blob/master/gunrock/util/array_utils.cuh#L377
3. comment out the Allocate and Move calls for row_offsets and column_indices at line 235 to line 240.

This is really a hack, but maybe the simplest way.
I'm afraid changing the APIs may introduce other issues, and that won't work if the CSR is accessed on CPU (for partitioning or other purposes).
@gumlym please try on your local copy, and I'm happy to help if you face any issue related to this.

**Comment by elalish** [comment]
+1 for this feature. Maybe you can leverage the way thrust tags vectors as host or device? Or just provide an execution policy input?

**Comment by neoblizz** [comment]
Feature supported in the refactored gunrock, this hasn't been tested yet.

https://github.com/gunrock/gunrock/blob/dev-refactor/gunrock/app/sssp/sssp_app.cu#L245
https://github.com/gunrock/gunrock/blob/dev-refactor/gunrock/app/sssp/sssp_app.cu#L280

Replace `util::HOST` with `util::DEVICE`.
