### ISSUE TITLE
atomic guard

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#242]
Massimiliano Fatica noted (when looking at our code) that:

> You should modify the pr_functor.cuh file in your repo, atomicAdd is now defined in CUDA8,
if you don’t guard the function, the compiler will give an error.

Assigning to @neoblizz but @yzhwang and @sgpyc please comment!

```
#if CUDA_VERSION < 8000
// atomic addition from Jon Cohen at NVIDIA
__device__ static double atomicAdd(double *addr, double val)
{
    double old=*addr, assumed;
    do {
        assumed = old;
        old = __longlong_as_double(
        atomicCAS((unsigned long long int*)addr,
               __double_as_longlong(assumed),
               __double_as_longlong(val + assumed)));
    } while( assumed!=old );
    return old;
}
#endif
```

**Comment by sgpyc** [comment]
We do have the atomic guard https://github.com/gunrock/gunrock/blob/master/gunrock/util/device_intrinsics.cuh#L23 , to only define some atomic functions when nvcc version is less than 8.0.
I don't think atomicAdd(double) is only defined for compute capability >=6.x, as the master branch is running on K40c. My guess is although the support is not native, its supported somehow like what we did.
But if there is any issue, I can enable that segment for NVCC <= 8.0 or CUDA_ARCH < 6.0.

**Comment by yzhwang** [comment]
It's defined in nvidia doc: https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#atomicadd
The reason that we are not facing this problem is probably because we are not using them? See pr's test: https://github.com/gunrock/gunrock/blob/master/tests/pr/test_pr.cu#L1070
I guess once we enable this in CUDA 8, we will somehow get a redefinition error during compile time?
The logic should be simple: For nvcc<8.0 or cuda_arch < 6.0, we use the customized version, otherwise use CUDA's native atomicAdd().
Actually I found out today that Tensorflow didn't add this too, so I just filed an internal bug, just in case you guys want to refer to the code, here's how Tensorflow's atomic wrappers work:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/util/cuda_kernel_helper.h#L153

**Comment by neoblizz** [comment]
`double` already has a guard on it in `device_intrinsics.cuh`, should the https://github.com/gunrock/gunrock/blob/master/gunrock/util/device_intrinsics.cuh#L48 also be protected? @yzhwang
