### ISSUE TITLE
Betweenness Centrality Performance

### ISSUE THREAD

**Issue by LeonHeTheFirst** [gunrock/gunrock#256]
gunrock_bc() runs multiple orders of magnitude slower than CPU implementations.

    struct GRTypes data_t;                 // data type structure
    data_t.VTXID_TYPE = VTXID_INT;         // vertex identifier
    data_t.SIZET_TYPE = SIZET_INT;         // graph size type
    data_t.VALUE_TYPE = VALUE_FLOAT;       // attributes type

    int test[1] = {-1};
    struct GRSetup *config = InitSetup(1, test);   // gunrock configurations

    gunrock_bc(out_graph, in_graph, config, data_t);

    return 0;

Here is the file I used for benchmarking. It has 4039 nodes and 88234 edges, which turns into 176468 edges in CSR format:
[facebook_combined.txt](https://github.com/gunrock/gunrock/files/1116257/facebook_combined.txt)

I was wondering if there are other arguments that need to be set anywhere

**Comment by jowens** [comment]
That is such a small graph, it's unlikely to run well on any GPU implementation. It's not nearly large enough to fill up the machine with work.

**Comment by neoblizz** [comment]
@LeonHeTheFirst could you share your results (timing for cpu and gpu)?

```
muhammad@blizzard:~/gunrock/build (dev)*$ ./bin/bc market ../dataset/small/facebook_combined.txt --traversal-mode=TWC
Loading Matrix-market coordinate-formatted graph ...
  Reading directly from stored binary CSR arrays ...
Done reading (0s).

Degree Histogram (4039 vertices, 176468 edges):
    Degree   0: 1 (0.02%)
    Degree 2^0: 75 (1.86%)
    Degree 2^1: 191 (4.73%)
    Degree 2^2: 388 (9.61%)
    Degree 2^3: 741 (18.35%)
    Degree 2^4: 907 (22.46%)
    Degree 2^5: 835 (20.67%)
    Degree 2^6: 597 (14.78%)
    Degree 2^7: 298 (7.38%)
    Degree 2^8: 2 (0.05%)
    Degree 2^9: 3 (0.07%)
    Degree 2^10: 1 (0.02%)

Using 1 GPU: [ 0 ].
Using traversal-mode LB
__________________________
0	 3	 0	 queue3 	 oversize :	 4848 ->	 14476
0	 3	 0	 queue3 	 oversize :	 4848 ->	 14476
0	 4	 0	 queue3 	 oversize :	 14476 ->	 134282
0	 4	 0	 queue3 	 oversize :	 14476 ->	 134282
--------------------------
iteration 0 elapsed: 2.344131 ms, src = 0
Computing reference value ...
CPU BC finished in 1.425982 msec. Search depth: 9

Validity BC Value: 
CORRECT
Validity Sigma: 
CORRECT
Validity labels: 
CORRECT

	Memory Usage(B)	 #keys0,0	 #keys0,1
GPU_0	 7340032	 134282	 4848
	 queue_sizing =	 33.246348 	 1.200297

 [BC] finished.
 avg. elapsed: 2.3441 ms
 iterations: 0
 min. elapsed: 2.3441 ms
 max. elapsed: 2.3441 ms
 rate: 150.2373 MiEdges/s
 src: 0
 nodes_visited: 4015
 edges_visited: 352176
 nodes queued: 8029
 edges queued: 176088
 nodes redundance: 99.98%
 load time: 135.6690 ms
 preprocess time: 5.9290 ms
 postprocess time: 2.8121 ms
 total time: 148.9849 ms
```

What @jowens said is true, you don't have the right workload to fill up the GPU resources, but @yzhwang also mentioned an optimization we could do to make it significantly faster, by launching multiple partial executions at once in parallel and accumulating the result at the end. I think it is slower because you have set it to compute complete bc.

**Comment by LeonHeTheFirst** [comment]
Sorry about the late response. I'm not sure how to do timing for GPU, but the total execution took 10 seconds on my machine with an i7-3635QM and GT750M.

**Comment by alexperrone** [comment]
@neoblizz is that run for your timing of "total time: 148.9849 ms" for 1 iteration, or does it do a complete run? That is, in reference to Issue #251 , is it equivalent of passing -1 or NULL? It took ~200 ms on my machine to run `./bin/bc` using your command. A CPU implementation using `igraph` takes around 2.3 seconds for a complete run, whereas using the configuration included by @LeonHeTheFirst above, it took around 32 seconds on `gunrock` for what seems to be a complete run.

**Comment by neoblizz** [comment]
It is for one iteration. @yzhwang can explain why we do 1 iteration instead of the full run. But the earlier statement still holds that the graph doesn't seem big enough to utilize a GPU's potential.

**Comment by jowens** [comment]
Pretty sure that the standard way BC is evaluated in the GPU world is one iteration (e.g., previous projects do the same thing), so we did this for comparison purposes. I think this is because doing a full BC run on a graph of significant size takes a really long time.

I think it's fair to say that for a large graph, you'd run Gunrock's BC from each vertex in sequence (@yzhwang, yes?) and each of those computations would itself fill the GPU (and thus run efficiently). But for a smaller graph, any individual one of those BC passes doesn't fill the GPU and doesn't run efficiently. To address smaller graphs like that, ideally we'd take a multi-BFS approach to BC [1]. Gunrock doesn't currently do that.

[1]	A. McLaughlin and D. A. Bader, “Scalable and high performance betweenness centrality on the GPU,” presented at the SC '14: Proceedings of the International Conference for High Performance Computing, Networking, Storage and Analysis, 2014, pp. 572–583.

**Comment by yzhwang** [comment]
Correct. When setting the source node to be -1, we will do the full run. Again, on the GPU only when the data size reaches a certain level can we get a large performance win. Basically these small tests are sanity tests to make sure that our code works as expected but not for performance benchmark purpose.

**Comment by neoblizz** [comment]
If you have further questions, reopen this issue and let us know. :)

**Comment by bharathbs93** [comment]
@neoblizz @jowens  Is there a comparison with [1] when doing full (i.e src = -1) BC with GUNROCK?


[1]	A. McLaughlin and D. A. Bader, “Scalable and high-performance betweenness centrality on the GPU,” presented at the SC '14: Proceedings of the International Conference for High-Performance Computing, Networking, Storage and Analysis, 2014, pp. 572–583.

**Comment by jowens** [comment]
I don't think we've ever run a full BC (for all nodes) on any significant-sized graph. It would take a very very long time, as you might imagine. `soc-orkut` takes about half a second to run per node, and with 3M nodes ... that's more than two weeks, if I'm doing my math right.

**Comment by bharathbs93** [comment]
@jowens Could a multi-BFS approach similar to [1] if incorporated to GUNROCK fasten this process?.

**Comment by jowens** [comment]
Sure! We admire Adam's work very much. But Gunrock currently doesn't have a notion of task parallelism, which would be necessary to implement what Adam did there.

**Comment by ctcyang** [comment]
@bharathbs93 We're looking to add something similar to a multi-BFS approach using a GraphBLAS backend, but no timeline on this feature yet!

**Comment by bharathbs93** [comment]
@jowens Thank you for the input.
