### ISSUE TITLE
Improve Gunrock building / compiling speed.

### ISSUE THREAD

**Issue by porumbes** [gunrock/gunrock#473]
**Feature Description:**

Compiling Gunrock and / or its various apps is much too slow. Faster compilation will 
* generally improve productivity
* make `printf` debugging easier (for those times when cuda-gdb doesn't seem to work)
* make it easier for new users to explore the codebase and see the results of their changes

**Describe the solution you'd like:**

I'd like to see faster build times.

**Comment by jdwapman** [comment]
I attempted some tweaks to compilation by having the Makefile only compile changed files. This appears to work for source files (.cpp, .cu), but from what I've been seeing online, nvcc doesn't support precompiling of .cuh header files, which is where quite a bit of Gunrock's code is. Perhaps it would be useful to separate these into .cu and .cuh files in the future?

**Comment by jdwapman** [comment]
```
# ----------------------------------------------------------------
# Gunrock -- Fast and Efficient GPU Graph Library
# ----------------------------------------------------------------
# This source code is distributed under the terms of LICENSE.TXT
# in the root directory of this source distribution.
# ----------------------------------------------------------------

#-------------------------------------------------------------------------------
# (make test) Test driver for ALGO
#-------------------------------------------------------------------------------

include ../BaseMakefile.mk
ALGO = hits
EXEC = bin/test_$(ALGO)_$(NVCC_VERSION)_$(ARCH_SUFFIX)
NVCCFLAGS += -lcurand

ALLDEPS = test_$(ALGO).cu $(DEPS)
HEADERS = $(filter %.cuh, $(ALLDEPS)) $(filter %.h, $(ALLDEPS))
CPPSRC = $(filter %.cpp, $(ALLDEPS))
CUSRC = $(filter %.cu, $(ALLDEPS))
CSRC = $(filter %.c, $(ALLDEPS))

# Use the sort function to prevent duplicates from .c and .cpp files
OBJECTS = $(sort $(CSRC:.c=.o) $(CPPSRC:.cpp=.o) $(CUSRC:.cu=.o))

all: $(ALLDEPS) $(EXEC)

a: $(EXEC)

$(EXEC) : $(OBJECTS) $(HEADERS)
	mkdir -p bin
	$(NVCC) $(DEFINES) $(SM_TARGETS) -o $@ $(OBJECTS) $(NVCCFLAGS) $(ARCH) $(INC) -O3

%.o: %.cu  $(ALLDEPS)
	$(NVCC) -c -o $@ $< $(NVCCFLAGS) $(DEFINES) $(SM_TARGETS) $(ARCH) $(INC)

%.o: %.c  $(ALLDEPS)
	$(NVCC) -c -o $@ $< $(NVCCFLAGS) $(DEFINES) $(SM_TARGETS) $(ARCH) $(INC)


%.o: %.cpp  $(ALLDEPS)
	$(NVCC) -c -o $@ $< $(NVCCFLAGS) $(DEFINES) $(SM_TARGETS) $(ARCH) $(INC)

# Uncommment this rule to NVCC fail at precompiling header files
#%.cuh: $(HEADERS)
#	$(NVCC) -c -o $@ $< $(NVCCFLAGS) $(DEFINES) $(SM_TARGETS) $(ARCH) $(INC)
```

**Comment by neoblizz** [comment]
One possible solution is to switch to Ninja as the default build system.

**Comment by neoblizz** [comment]
This is future work, I can't get something more performant than "just use ninja" to work as of right now.

**Comment by porumbes** [comment]
Adding @neoblizz 's comment from Mark Harris: https://twitter.com/harrism/status/1153830299584757762?s=19

**Comment by crozhon** [comment]
Wanted to bump this discussion a bit with more info. Changes to the core gunrock library (changing a file within oprtr, or one of the XXX_base.cuh files) cause very long rebuilds. This is due to Gunrock breaking some conventions with its file structure. Gunrock includes many .cuh files into a singular compiled object, rather than having seperate objects for distinct classes and components. When any of these headers change, the entirely of the gunrock shared library changes as well There's multiple avenues we can go down to change this:

* Incremental linking. A lot of the object code we are using isn't actually changing. In theory, incremental linking should be helping us a great deal. The issue is that CUDA and NVCC's inlining of all device functions might eliminate this as an option.
* Change .cu to .cpp, etc. This is related to Mark Harris' comments. This should include some type of improvement. But I'm not sure how much this can be done. We intersperse device code throughout our files. 
* Restructure includes. Split gunrock into logical components using existing files. The simplest way to do this is a very common C++ idiom, each class has both a header and an object file. The header is included in the object, and is included by other objects which reference these functions. Each file would then be compiled into a separate ".o" file and these ".o" files are linked into a singular ".so" or ".a" file at the end. Using the Gunrock library would then require including a header and linking against this library. Instead we currently combine all Gunrock source code (through headers) into a single shared library, or we combine it with the app you're making into a single binary. I'm not sure why we went in this direction initially, so I might be missing something about these choices. Could @neoblizz or @porumbes comment on it more?

**Comment by jowens** [comment]
@achalagarwal here's the central place to discuss build times/strategy

**Comment by achalagarwal** [comment]
@jowens Thanks

@crozhon Do you think it would help if I spend some time changing our Cmake to one based purely on target + properties. 

There could be some duplicate (redundant) building that we might be able to fix with that. 



That might also help utilise multiple threads better as the dependency graph could possibly be understood better. 

The alternative is to modify the parts in our existing Cmake which are resulting in the redundant builds and/or breaking the monolithic dependencies to better parallelize the build.

**Comment by porumbes** [comment]
@achalagarwal if you have an easy experiment in mind, I say go for it, but it might be best in the short term to switch over to ninja as @neoblizz suggests (~50% reduction in build time).

**Comment by crozhon** [comment]
I also say go for it if you can, but I think that the biggest factor comes from building and linking the gunrock file as a few relatively large objects, rather than many object files over several different translation units. Which is why 'make -k bfs' is still relatively slow, even though it's just building the one binary.

**Comment by achalagarwal** [comment]
C++20 is introducing modules and Cmake is has started working on integrating that. It's not going to be soon because it requires a fundamental change as the cpp files now require an ordered compilation. 

Naturally this means that if we plan to move to modules, we would have to rework our Cmake (reasonable guess). 

Also I'll try to read up how modules can or will help if we do want to use it. 

But before thinking that far, would we want to move to c++20 in the near future?

**Comment by neoblizz** [comment]
> But before thinking that far, would we want to move to c++20 in the near future?

CUDA only supports C++17, so, no.
