### ISSUE TITLE
If you pass a bogus filename as the input matrix, you get a non-helpful output

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#69]
`Unable to open file: No such file or directory
Unable to open file: No such file or directory
[/home/jowens/working/gunrock/gunrock/util/array_utils.cuh, 510 @ gpu 0] row_offsets cudaMemcpy H2D failed (CUDA error 11: invalid argument)`

A much more meaningful error message would be nice. Perhaps assign to one of the new students?

**Comment by wetliu** [comment]
I want to try this problem. How can do I need to get assigned?

**Comment by jowens** [comment]
@wetliu On the right side of this page is "Assignee". Assign yourself!

**Comment by sgpyc** [comment]
One more thing about input: if passing invalid arguments, like -undirected (missing one -), --undirect (wrong argument), --undirected --undirected (twice), --device=0, --device=1,2 (twice with different values), the behavior now is not as expected.

**Comment by jowens** [comment]
@sgpyc that should be a different issue, don't wedge it into this one

**Comment by sgpyc** [comment]
Moved to issue #91 , thanks @jowens

**Comment by wetliu** [comment]
The gunrock has the exception case for inputting the wrong file name. Thanks for the help from gunrock team, I edited a little bit and right now it can catch the bogus file name. 

However, I need some help in identifying what the main function will do if the LoadGraph is has an error. The output right now is this:

weitang@slaking:~/gunrock/tests/bc/bin$ ./test_bc_7.5_x86_64 market ../test_bc.mLoading Matrix-market coordinate-formatted graph ...
Input graph does not exist.
Using 1 GPU: [ 0 ].
 [../../gunrock/util/array_utils.cuh, 510 @ gpu 0] row_offsets cudaMemcpy H2D failed (CUDA error 11: invalid argument)
Computing reference value ...
Segmentation fault (core dumped)

I hope to stop executing the function afterwards instead of getting the seg fault at the end. Thank you!

**Comment by sgpyc** [comment]
Maybe capture the cudaError_t returned by info->Init("BFS", *args, csr);, if it's not cudaSuccess, then stop the program / throw an exception. Same checking should be added to Init and Reset for both problem and enactor.

**Comment by sgpyc** [comment]
Invalid filename now stops the program, with a suitable error message.

```
sgpyc@mario:~/Projects/gunrock_master/examples/bfs$ ./bin/test_bfs_9.1_x86_64 market /data/haha
Loading Matrix-market coordinate-formatted graph ...
Input graph file /data/haha does not exist.
sgpyc@mario:~/Projects/gunrock_master/examples/bfs$ ./bin/test_bfs_9.1_x86_64 market nothing
Loading Matrix-market coordinate-formatted graph ...
Input graph file nothing does not exist.
sgpyc@mario:~/Projects/gunrock_master/examples/bfs$ ./bin/test_bfs_9.1_x86_64 market /data/gunrock_dataset/large
Loading Matrix-market coordinate-formatted graph ...
Reading from /data/gunrock_dataset/large:
  Parsing MARKET COO format
Invalid graph, first line cannot be empty.
```
