### ISSUE TITLE
gunrock static library build fails

### ISSUE THREAD

**Issue by ChuckHastings** [gunrock/gunrock#703]
**Summary:**
If you attempt to build gunrock as a static library, the build fails.  It appears that some of the examples need to have a shared library.  Perhaps cmake needs to be configured to skip those files if we're not building a shared library.

**Reproducibility:**
Always

**To Reproduce:**
1. Clone gunrock
1. Switch to the dev branch
1. Update submodules
1. `cmake .. -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DGPU_ARCHS="" -DGUNROCK_BUILD_SHARED_LIBS=OFF`
1. `make -j 4`. (*** pick your favorite parallelism or run without -j in serial)

**Expected Behavior:**
The make in the last step should succeed.  The build/lib directory should contain libgunrock.a.

**Actual Results:**
The make fails with a link error.  It appears that the static library is build correctly, however there are several shared library executables that don't build properly.

**System Configuration:**

GPU: GV100
CPU: Intel(R) Xeon(R) Gold 6128 CPU @ 3.40GHz
OS: Ubuntu 16.04.1 LTS
Cuda compilation tools, release 10.1, V10.1.243
NVIDIA-SMI 418.87
Driver Version: 418.87
CUDA Version: 10.1
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609

**Comment by ChuckHastings** [comment]
FYI - I workaround this by also setting -DGUNROCK_BUILD_TESTS=OFF

**Comment by crozhon** [comment]
Hi Chuck, thanks for reporting. I can reproduce and I'm working on the fix now.

**Comment by crozhon** [comment]
I've pushed a fix to dev for this. The issue was that CMake wasn't picking up g++ for linking the examples like it used to. So it failed to find references for the std lib. I explicitly set CMake to use the C++ linker for this step and it solved the problem. 

Thanks for letting us know about this. We should also consider not building the examples when we make a static lib.
