### ISSUE TITLE
Number of instructions in kernels

### ISSUE THREAD

**Issue by mahmoodn** [gunrock/gunrock#720]
For the following output
```
[bfs] finished.
 avg. elapsed: 4037751.556158 ms
 iterations: 6262
 min. elapsed: 4037751.556158 ms
 max. elapsed: 4037751.556158 ms
 rate: 0.014292 MiEdges/s
 src: 0
 nodes_visited: 23947347
 edges_visited: 57708624
 nodes queued: 23947347
 load time: 5224.63 ms
 preprocess time: 2204.690000 ms
 postprocess time: 492.286921 ms
 total time: 4040449.452877 ms
```
I want to know if `nodes_visited` is the total visited nodes for the number of `iterations`, or not. Any thought?
Also, for the road_usa input, I see that each iterations of RelaxLightEdges has few number of thread instructions, e.g. 83K instructions. With 6262 invocations, the number of thread instructions are about 520M.
For GetEdgeCounts, the thread instructions for each iteration is about 3K and the number of invocations is about 12K. So, the total number of thread instructions is 36M.

I would like to know if these numbers are reliable for a graph with 23M vertices...

**Comment by neoblizz** [comment]
Yes, that should be for all iterations: 
https://github.com/gunrock/gunrock/blob/master/gunrock/util/info_rapidjson.cuh#L578-L600

**Comment by neoblizz** [comment]
> Also, for the road_usa input, I see that each iterations of RelaxLightEdges has few number of thread instructions, e.g. 83K instructions. With 6262 invocations, the number of thread instructions are about 520M.
> For GetEdgeCounts, the thread instructions for each iteration is about 3K and the number of invocations is about 12K. So, the total number of thread instructions is 36M.
> 
> I would like to know if these numbers are reliable for a graph with 23M vertices...

It's really difficult for us to answer that because we don't use performance counters at the architectural level. This could be very different for different GPU architectures. For example, some GPU archs can support vectorized load/stores reducing instruction count. We would love for someone to spend some more time on this and profile this for us, and give us feedback on two things:
1. How can we improve gunrock overall with maybe minimizing the instructions, or utilizing them better,
2. What feedback we can give to NVIDIA for sparse problems such as graphs to improve their architectural approach.
