### ISSUE TITLE
rgg dataset download link is stale

### ISSUE THREAD

**Issue by yzhwang** [gunrock/gunrock#73]
rgg dataset is part of our standard tests. So we need to provide the dataset or ways to generate the dataset.
https://github.com/gunrock/gunrock/blob/master/dataset/large/rgg_n_2_24_s0/readme.txt
The google drive link is expired, we need a stable place to store this dataset, or provide a script/program to generate this rgg graph. @sgpyc can you take charge of this?

**Comment by neoblizz** [comment]
@yzhwang 
1. Where can I find the dataset that was on the google drive? 
2. We need to generate a random geometric graph or find a way to provide the dataset (which one would you prefer)? 
Can I get some more information on how you want this done?

**Comment by yzhwang** [comment]
Actually, I checked the link is not expired, the reviewer said so because in the paper there is a linebreak in the link, I've fixed this and it can be downloaded here:
https://drive.google.com/uc?export=download&id=0Bw6LwCuER0a3VWNrVUV6eTZyeFU

For dataset with such large size, I don't have a good idea right now. I think a script/program to generate not only rgg but also r-mat graph would be great. Actually, we have both rgg and rmat class here: https://github.com/gunrock/gunrock/tree/master/gunrock/graphio Maybe you can write some small programs to let people generate rgg and rmat graph with a full set of parameters and write to mtx  (or binary) file here:
https://github.com/gunrock/gunrock/tree/master/tools

If you can find easier way to do this (e.g. using python, or other scripting language), just try your way!

**Comment by neoblizz** [comment]
@yzhwang Got it! I will work on the script for this, sounds like an interesting issue. I was wondering if we have a server for the website where we're hosting gunrock's main site, maybe allow them also to download it from there instead of google drive, since we will be able to manage it (this is an idea in addition to the script).

**Comment by jowens** [comment]
@neoblizz If you want to host it somewhere, make another github repo under the gunrock org and host it there. We don't want to be in the business of maintaining a web server.

**Comment by neoblizz** [comment]
Progress update: I am able to generate *.mtx files with a data, a few things came up when discussing this issue with @yzhwang the implementation using gunrock/graphio/rgg.cuh was that the function `BuildRggGraph` assigns the graph to `csr` instead of giving an option to write to .mtx file or .csr. A possible fix and better implementation will be having `BuildRggGraph` just generate the rgg and then call a function which assigns the `csr` (basically separating the two). Also, this issue then evolved into supporting multiple graph types instead of just *.mtx. Any comments or critiques on my approach?

**Comment by jowens** [comment]
Separating input/generation and output, as you suggest, seems sensible to me. Then the question is "what is the internal representation"; input/generation produces what format? and output starts from what internal format?

**Comment by neoblizz** [comment]
My suggestion; Input/generation produces `typedef Coo<VertexId, Value>;` which can be used to allocate the graph to either `csr` or an output file. There are variety of output files that I can code this into, but the first one will be `mtx` format.

Output starts from the same `Coo` internal format, defined here: https://github.com/gunrock/gunrock/blob/master/gunrock/coo.cuh

**Comment by jowens** [comment]
I'm agnostic on what it should be. @yzhwang and @sgpyc ought to have an opinion ...

**Comment by yzhwang** [comment]
@neoblizz Since most graph file format represent graph as edge list (mtx, gr, snap). I think using Coo as the internal format for taking the graph file input is sensible. We might need to change some design of coo and csr for both better performance and better usability. We can discuss this in person.
