### ISSUE TITLE
what's happening with this dobfs/orkut run?

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#78]
Besides the fact it doesn't appear to work, it also reads the mtx file twice (with different histogram results), which is kind of weird.

Appears to be a consequence of selecting `-directed`. Only the livejournal and indochina datasets work with `--directed`. DOBFS, BFS: same issue with both.

```
mario 504$ ../../gunrock-build/bin/direction_optimizing_bfs market /data/gunrock_dataset/large/soc-orkut/soc-orkut.mtx --device=1 --src=0 --idempotence --mark-pred --alpha=2 --beta=2 --iteration-num=10
Loading Matrix-market coordinate-formatted graph ...
Reading from /data/gunrock_dataset/large/soc-orkut/soc-orkut.mtx:
  Parsing MARKET COO format (2997166 nodes, 106349209 directed edges)... Done parsing (34s).
  Converting 2997166 vertices, 106349209 directed edges (unordered tuples) to CSR format...
Done converting (4s).

Degree Histogram (2997166 vertices, 106349209 edges):
    Degree   0: 1005 (0.03%)
    Degree 2^0: 92480 (3.09%)
    Degree 2^1: 158955 (5.30%)
    Degree 2^2: 316144 (10.55%)
    Degree 2^3: 561754 (18.74%)
    Degree 2^4: 766179 (25.56%)
    Degree 2^5: 672335 (22.43%)
    Degree 2^6: 320814 (10.70%)
    Degree 2^7: 85094 (2.84%)
    Degree 2^8: 20065 (0.67%)
    Degree 2^9: 2236 (0.07%)
    Degree 2^10: 100 (0.00%)
    Degree 2^11: 5 (0.00%)

Loading Matrix-market coordinate-formatted graph ...
Reading from /data/gunrock_dataset/large/soc-orkut/soc-orkut.mtx:
  Parsing MARKET COO format (2997166 nodes, 106349209 directed edges)... Done parsing (34s).
  Converting 2997166 vertices, 106349209 directed edges (unordered tuples) to CSR format...
Done converting (4s).

Degree Histogram (2997166 vertices, 106349209 edges):
    Degree   0: 319138 (10.65%)
    Degree 2^0: 176555 (5.89%)
    Degree 2^1: 259492 (8.66%)
    Degree 2^2: 365347 (12.19%)
    Degree 2^3: 471207 (15.72%)
    Degree 2^4: 521643 (17.40%)
    Degree 2^5: 451460 (15.06%)
    Degree 2^6: 275359 (9.19%)
    Degree 2^7: 111832 (3.73%)
    Degree 2^8: 34915 (1.16%)
    Degree 2^9: 8240 (0.27%)
    Degree 2^10: 1262 (0.04%)
    Degree 2^11: 451 (0.02%)
    Degree 2^12: 172 (0.01%)
    Degree 2^13: 71 (0.00%)
    Degree 2^14: 22 (0.00%)

Source vertex: 0
Using 1 GPU(s): [ 1 ].
 alpha = 2.0000, beta = 2.0000
 computing reference value ...
CPU BFS finished in 0.001907 msec. Search depth is: 1


First 40 labels of the GPU result.
[0:0 1:-1 2:-1 3:-1 4:-1 5:-1 6:-1 7:-1 8:-1 9:-1 10:-1 11:-1 12:-1 13:-1 14:-1 15:-1 16:-1 17:-1 18:-1 19:-1 20:-1 21:-1 22:-1 23:-1 24:-1 25:-1 26:-1 27:-1 28:-1 29:-1 30:-1 31:-1 32:-1 33:-1 34:-1 35:-1 36:-1 37:-1 38:-1 39:-1 ]

 [DOBFS] finished.
 elapsed: 0.1892 ms
 iterations: 0Fewer than 5 vertices visited.


	Memory Usage(B)	 #keys0,0	 #keys0,1
GPU_1	 2221023232	 106349211	 106349211
	 queue_sizing =	 35.483257 	 35.483257
```

**Comment by yzhwang** [comment]
Reading graph file twice is redundant. This is related to Issue 71: https://github.com/gunrock/gunrock/issues/71
dobfs needs both csr and csc (even for directed graph), we should have a csr2csc() function to turn csr into csc in memory.

If you add --mark-pred flag, the results cannot be validated because any parent of a node can claim it as its child. So there is no "CORRECT". The seemingly wrong results comes from our changing to the .mtx loading process:
https://github.com/gunrock/gunrock/commit/9e159144fc8713e90c7f5ecc8634f83d7fe53221#diff-9f1180b55bbb1d98cf19a13897694593L174
Before this change, when we load soc-orkut as directed graph, the first node will have several neighbors because the edge list looks like the following:
2 1
3 1
4 1
...
But now the graph thinks the first node has no outgoing edge, and node 2,3,4 all point to node 1. Hence the "fewer than 5 nodes are visited" result.
I am still not sure about the correct order of mtx file (row major or col major). From the matrices on U Florida Sparse Matrix Library, it seems that it should be column major, but the official definition is row major (http://math.nist.gov/MatrixMarket/formats.html). So now we are using row major.

**Comment by jowens** [comment]
All I care about is that we either a) get a meaningful result or b) an error message that tells us that we can't get a meaningful result. If `--mark-pred` is incompatible with a particular graph, then let's say so.

**Comment by jowens** [comment]
Same thing happens with `--directed` without `--mark-pred`, btw.

```
mario 507$ ../../gunrock-build/bin/direction_optimizing_bfs market /data/gunrock_dataset/large/soc-orkut/soc-orkut.mtx --device=1 --src=0 --idempotence --directed --alpha=2 --beta=2 --iteration-num=10
Loading Matrix-market coordinate-formatted graph ...
Reading from /data/gunrock_dataset/large/soc-orkut/soc-orkut.mtx:
  Parsing MARKET COO format (2997166 nodes, 106349209 directed edges)... Done parsing (34s).
  Converting 2997166 vertices, 106349209 directed edges (unordered tuples) to CSR format...
Done converting (4s).

Degree Histogram (2997166 vertices, 106349209 edges):
    Degree   0: 1005 (0.03%)
    Degree 2^0: 92480 (3.09%)
    Degree 2^1: 158955 (5.30%)
    Degree 2^2: 316144 (10.55%)
    Degree 2^3: 561754 (18.74%)
    Degree 2^4: 766179 (25.56%)
    Degree 2^5: 672335 (22.43%)
    Degree 2^6: 320814 (10.70%)
    Degree 2^7: 85094 (2.84%)
    Degree 2^8: 20065 (0.67%)
    Degree 2^9: 2236 (0.07%)
    Degree 2^10: 100 (0.00%)
    Degree 2^11: 5 (0.00%)

Loading Matrix-market coordinate-formatted graph ...
Reading from /data/gunrock_dataset/large/soc-orkut/soc-orkut.mtx:
  Parsing MARKET COO format (2997166 nodes, 106349209 directed edges)... Done parsing (34s).
  Converting 2997166 vertices, 106349209 directed edges (unordered tuples) to CSR format...
Done converting (4s).

Degree Histogram (2997166 vertices, 106349209 edges):
    Degree   0: 319138 (10.65%)
    Degree 2^0: 176555 (5.89%)
    Degree 2^1: 259492 (8.66%)
    Degree 2^2: 365347 (12.19%)
    Degree 2^3: 471207 (15.72%)
    Degree 2^4: 521643 (17.40%)
    Degree 2^5: 451460 (15.06%)
    Degree 2^6: 275359 (9.19%)
    Degree 2^7: 111832 (3.73%)
    Degree 2^8: 34915 (1.16%)
    Degree 2^9: 8240 (0.27%)
    Degree 2^10: 1262 (0.04%)
    Degree 2^11: 451 (0.02%)
    Degree 2^12: 172 (0.01%)
    Degree 2^13: 71 (0.00%)
    Degree 2^14: 22 (0.00%)

Source vertex: 0
Using 1 GPU(s): [ 1 ].
 alpha = 2.0000, beta = 2.0000
 computing reference value ...
CPU BFS finished in 0.002146 msec. Search depth is: 1

Validity:
CORRECT
First 40 labels of the GPU result.
[0:0 1:-1 2:-1 3:-1 4:-1 5:-1 6:-1 7:-1 8:-1 9:-1 10:-1 11:-1 12:-1 13:-1 14:-1 15:-1 16:-1 17:-1 18:-1 19:-1 20:-1 21:-1 22:-1 23:-1 24:-1 25:-1 26:-1 27:-1 28:-1 29:-1 30:-1 31:-1 32:-1 33:-1 34:-1 35:-1 36:-1 37:-1 38:-1 39:-1 ]

 [DOBFS] finished.
 elapsed: 0.1817 ms
 iterations: 0Fewer than 5 vertices visited.


	Memory Usage(B)	 #keys0,0	 #keys0,1
GPU_1	 2221023232	 106349211	 106349211
	 queue_sizing =	 35.483257 	 35.483257
```

**Comment by yzhwang** [comment]
--mark-pred cannot be validated even using atomic. It can only be validated if the algorithm force the parent with the smallest node ID to claim its child. This feature is for people who want to trace back the visiting paths. I checked the code and found that it does not work with --idempotence too, because of the way we implement the kernel. I will update the information in our Usage() to indicate this. Making mark-pred and idempotence work together may need some interface change. I will talk with @sgpyc about this.

For the all -1 results, it is due to the change of mtx file loading order. Now using the row major, the graph's first node becomes a dangling node, that is why all the neighbors have no predecessor, nor labels (because they are not visited). I think we could add an option to let user specify row major or col major when they load mtx file.

**Comment by jowens** [comment]
OK. Maybe close this issue and open the issues it created? :) It is just fine if we say "these are not compatible options, we're not gonna run this".

**Comment by sgpyc** [comment]
I remember in some version we check the labels of output preds (the correct pred should have edge to the child and has label 1 less then the child)? That will validate the preds

**Comment by yzhwang** [comment]
@sgpyc That's right, the validation method should be different, and we need label value to help us. OK, I will create another issue on improving mark-pred validation. Thanks guys!
