### ISSUE TITLE
PageRank numbers are too good

### ISSUE THREAD

**Issue by ctcyang** [gunrock/gunrock#813]
**Summary:**
Using the [numbers](https://github.com/gunrock/io/blob/master/gunrock-output/v1-0-0/pr/K40c/soc-orkut/pr_soc-orkut_Tue%20Sep%20%201%20153103%20750%202020.json) provided by @neoblizz and comparing against the hardwired implementation (CuSha) and GraphBLAST numbers from the [GraphBLAST paper](https://arxiv.org/abs/1908.01407) which are both using highly-optimized SpMV implementations and pull for PageRank, Gunrock is significantly faster (over 10x). However, Gunrock is not specialized into optimizing for SpMV, so this leads me to think there may be a bug somewhere in the timing code or pull implementation. All times are in milliseconds.

For comparison, Gunrock v0.4 was still using push to do SpMV and the numbers there look more sane, so there could have been a possible regression introduced between v0.4 (push) and v1.0 (pull).

PR | Hardwired | Gunrock v0.4 | Gunrock v1.0 | GraphBLAST | Gunrock speedup over hardwired
-- | -- | -- | -- | -- | --
soc-orkut | 52.54 | 173.1 | 83.20 | 64.2223 | 0.63149038
soc-LiveJournal1 | 33.61 | 54.1 | 3.6 | 21.5454 | 9.33611111
hollywood-09 | 34.71 | 20.05 | 4.11 | 8.11912 | 8.44525547
indochina-04 | 164.6 | 41.59 | 12.1 | 19.1587 | 13.6033058
rmat_s22_e64 | 188.5 | 304.5 | 9.92 | 115.6 | 19.0020161
rmat_s23_e32 | 147 | 397.2 | 10.94 | 161.33 | 13.4369287
rmat_s24_e16 | 128 | 493.2 | 12.26 | 211.548 | 10.4404568
rgg_n_2_24_s0 | 53.93 | 181.3 | 11.94 | 34.5853 | 4.51675042
road_usa | 0 | 24.11 | 33.66 | 26.9053 | 0

**Reproducibility:**
Always

**To Reproduce:**
Detail the steps necessary to reproduce the behavior.

https://github.com/gunrock/io/blob/master/gunrock-output/v1-0-0/pr/K40c/soc-orkut/pr_soc-orkut_Tue%20Sep%20%201%20153103%20750%202020.json

**Expected Behavior:**
Gunrock PageRank to be around same performance as the highly optimized SpMVs.

**Actual Results:**
A clear and concise description of what you actually experienced.

**System Configuration:**

https://github.com/gunrock/io/blob/master/gunrock-output/v1-0-0/pr/K40c/soc-orkut/pr_soc-orkut_Tue%20Sep%20%201%20153103%20750%202020.json

**Comment by jowens** [comment]
@crozhon can you take an initial pass at this? results are in:

https://github.com/owensgroup/graphblast-paper/issues/20

**Comment by crozhon** [comment]
Will do!

**Comment by neoblizz** [comment]
The JSON that you linked have `"avg-process-time": 4160.194529427423,`, but in the table above you have `15.56`? Is that the right JSON? I am confused a bit.

**Comment by ctcyang** [comment]
For soc-orkut, I accidentally took the Titan V time of 15.5, but I've now corrected that one to `83.20 = 4160.19 / max-iter` where `max-iter = 50`. This number corresponds to what's displayed in this [Table](https://github.com/owensgroup/graphblast-paper/issues/20#issuecomment-686787295).

**Comment by neoblizz** [comment]
Yeah, just realized all the others are still much faster. Weird.

**Comment by jowens** [comment]
@crozhon just seeing if any insight on this, thanks.

**Comment by crozhon** [comment]
I would like to run PR on a K40C machine with soc-orkut so I can compare the timings specifically. The timings are so small for some of those that they don't look correct at all. I'm waiting for the cluster to come back up for that, but I can work around it if it's urgent. I've tried pagerank on my local machine just to check for correctness and I did not obtain strange numbers like these so it might be K40 specific, or it might be caused my multi-device. My first thought is that there is an error that caused it to return early.

Are these numbers from the latest revision? The JSON you linked is from SHA [47857e477a707f69484b6d77822195eb6b781d01](https://github.com/gunrock/gunrock/commit/47857e477a707f69484b6d77822195eb6b781d01), so it's possible these issues may have been fixed and that's why I don't see it locally. 

Since I'm waiting for that, I looked for obvious things in pr_app or pr_test.cuh (like an extra division by the number of iterations), but I didn't see anything noteworthy. The JSON code also looks ok at first glance. Do you see anything like that in the plotting / data gathering code? Or can you link me and I'll take a look?

**Comment by crozhon** [comment]
Leaving some of the data from my tests below, but things seem ok on a 2080. I want to check K40C and multi-gpu for issues now.

```
./bin/pr market ../dataset/large/road_usa/road_usa.mtx 

Rank Validity: PASS
Reference total rank : 1.000000
Maximum difference : rank[11825501] 0.000000 vs. 0.000000, 0.000000
Maximum relative difference :rank[16012959] 0.000000 vs. 0.000000, 0.000000
Order Validity: PASS
[pr] finished.
 avg. elapsed: 201.889992 ms
 iterations: 30
 min. elapsed: 201.889992 ms
 max. elapsed: 201.889992 ms
 nodes queued: 694473063
 edges queued: 1731258720
 nodes redundance: inf
 edges redundance: inf
 load time: 13239.9 ms
 preprocess time: 820.536000 ms
 postprocess time: 2167.305946 ms
 total time: 3191.439867 ms
```
```
./pr market ../../dataset/large/soc-orkut/soc-orkut.mtx 

Rank Validity: PASS
Reference total rank : 0.150000
Maximum difference : rank[2997166] 0.000000 vs. 0.000000, 0.000000
Maximum relative difference :rank[2997166] 0.000000 vs. 0.000000, 0.000000
Order Validity: PASS
[pr] finished.
 avg. elapsed: 546.279907 ms
 iterations: 3
 min. elapsed: 546.279907 ms
 max. elapsed: 546.279907 ms
 nodes queued: 5994334
 edges queued: 328042140
 nodes redundance: inf
 edges redundance: inf
 load time: 11930.4 ms
 preprocess time: 261.667000 ms
 postprocess time: 61.419964 ms
 total time: 869.553089 ms
```

**Comment by jowens** [comment]
https://github.com/gunrock/io/blob/master/scripts/graphblast-pull-pr-200901.py

note: `normalizePRByIterations`, which is in:

https://github.com/gunrock/io/blob/master/scripts/filters.py (line 148)
`        df["avg-process-time"] / df["max-iter"]`

That's where I do the normalization.

**Comment by crozhon** [comment]
Thanks for sharing - that helps. 

I'm confused a bit by the `max-iter` parameter, but I'm unfamiliar with how we report pagerank times. I looked at the paper and saw "All PageRank times are normalized to one iteration". So do we run (upto) `max-iter` iterations of the pagerank algorithm, then divide that runtime by `max-iter` to obtain the average per-iteration runtime? Do we always execute `max-iter` iterations? Or can we terminate with fewer iterations? Would dividing by the maximum still be correct in that case? 

For example, soc-orkut reports 3 iterations in my above output. "iterations" is the same value referenced as the stop condition and compared against max-iter:

https://github.com/gunrock/gunrock/blob/6dd8c736cb7ca27f95642c3f96343a33ae168030/gunrock/app/pr/pr_app.cu#L121
https://github.com/gunrock/gunrock/blob/6dd8c736cb7ca27f95642c3f96343a33ae168030/gunrock/app/pr/pr_enactor.cuh#L307

So should we divide the runtime of 546ms by 50 iterations or by 3 iterations? It seems the JSON output does not include the latter number at all.

**Comment by jowens** [comment]
So I don't think I know why those two params should diverge. Like, why would we stop at `iterations` if we'd specified a larger `max-iterations`? 

Almost certainly we should divide by the number of actual iterations because runtime should track those.

Background: Before Gunrock, most (all?) papers would report per-iteration PR times. I think this is because there was not a consensus on how many iterations it should take, and probably some papers didn't ever check for convergence and so different papers would use a different number of iterations. So that's why we do this. But, we need to actually check the number of iterations we can. But I don't know why we stop after 3 in this case. The code you point to in `pr_enactor` should run up to `max-iterations` and only stop then.

**Comment by crozhon** [comment]
Ok so there is definitely something wrong with us never reporting `iterations` in the JSON then. I can start by reporting the number of iterations taken as an additional JSON field. We can then rerun with a K40C and get proper times. 

@neoblizz Do you know why PR would stop before `max-iterations` have occurred? It seems to happen if no vertices were updated.

**Comment by crozhon** [comment]
Rerunning all of the datasets on mario right now. Should be done overnight if everything goes well. There will be a new field "elapsed-iterations" that specifies the elapsed iterations for each run.

**Comment by crozhon** [comment]
Finished a lot sooner than I expected, so I added the results to [io/gunrock-output/pr-iteration-rerun/](https://github.com/gunrock/io/tree/master/gunrock-output/pr-iteration-rerun). They have the tag `pr-iteration-rerun` and include the new field `elapsed-iterations`. 

`elapsed-iterations` is a `num-runs` sized array. If it exists, it specifies the actual number of iterations performed for every run of the problem. On the other hand, the field `max-iter` is an upper bound on the number of iterations performed and doesn't specify how many were executed. 

Do we have any other programs, besides Pagerank, that need the number of iterations that were executed for a single run?

**Comment by ctcyang** [comment]
The new numbers make a lot more sense. PageRank was the only program that I was having trouble with. Thank you for the fix!
