### ISSUE TITLE
Running IPDPS'20 dynamic graphs on GunRock

### ISSUE THREAD

**Issue by abasak24** [gunrock/gunrock#843]
Hi, 
I am new to Gunrock and am trying to perform some experiments on the dynamic data structure proposed in IPDPS'20. I have the following issues I am running into. If you could point out how to work around them, it would be great! My infrastructure is NVIDIA Tesla V100 GPU with 16GB memory.

1) In the gunrock/build/bin/, I am running the following command line using the livejournal dataset provided in the gunrock/dataset/large/ folder.  However, I keep on receiving the error shown below. Do you have some suggestions on how to resolve this issue? 

./dynamic_graph market ../../dataset/large/soc-LiveJournal1/soc-LiveJournal1.mtx

![image](https://user-images.githubusercontent.com/18584733/105912713-b80b6680-5fe0-11eb-9cfb-d48d75b2e7bb.png)

2) It looks like the command line in 1) is running the bulk_build experiment in the IPDPS'20 paper (Section VI.B.1). How is it possible to perform the batched insertion/deletion/vertex deletion experiments in the paper? Could you please provide some reference scripts/command lines for that? How to set the batch size? Especially for the batched deletion (edge or vertex), how was the input created? 

Thank you!

**Comment by abasak24** [comment]
Hi, I wanted to follow up on this. Some pointers would be very helpful. Thanks!

**Comment by maawad** [comment]
Hi @abasak24, the problem you ran into is easy to fix. [Allocate](https://github.com/gunrock/gunrock/blob/dynamic-graph/gunrock/graph/dynamic_graph/slabhash_graph_base.cuh#L68) need to be passed the correct parameters. I'll fix it. 

I currently don't have a similar benchmarking code for edge insertion or deletion, but there are examples here: 

- Deletion in undirected weighted [here](https://github.com/gunrock/gunrock/blob/dynamic-graph/unittests/test_dynamic_graph.h#L234)
- Deletetion in directed weighed [here](https://github.com/gunrock/gunrock/blob/dynamic-graph/unittests/test_dynamic_graph.h#L310)

There are also similar tests in the file for weighted edge insertion/deletion and building for undirected and directed graphs. 

So, this [file](https://github.com/gunrock/gunrock/blob/dynamic-graph/examples/dynamic_graph/test_dynamic_graph.cu) can be easily modified to perform edge insertion/deletion. I can add this sometime later.

For vertex insertion, this assumed to be edge insertion as long as the graph was constructed with enough vertices capacity. Vertex deletion is not currently implemented here.

In general,  random edges or vertices for any operation were generated randomly between 0: `num_vertices`, and duplicate edges were allowed to be generated, and the data structure handles maintaining uniqueness.

**Comment by maawad** [comment]
Should be fixed in https://github.com/gunrock/gunrock/pull/846. I ran the bulk build benchmark using the different data sets in the paper and the numbers are within milliseconds (Additional counters were added compared to the paper version, so a small increase is expected).

The only issue is with the graph `rgg_n_2_24_s0` my current numbers are 97.886 ms compared to 0.697 ms in the paper.  The paper number is probably wrong but I'll have to check my old implementation.

**Comment by abasak24** [comment]
@maawad Thank you for fixing the issue with allocate. It is working now. Thanks for your suggestions on performing batched insertion/deletion experiments. I have a lingering question on the experiment setup for Table II and Table III in the paper (I understand that Table IV is not reproducible because vertex deletion is not implemented here yet). 

For example, in Table II's (Table III's) experiments, let's say soc-LiveJournal1 was first entirely built in GPU memory and then a batch of a given size (2^16-2^22) of randomly generated edges were inserted (deleted) into the already-entirely-built soc-LiveJournal graph? Or is my understanding incorrect? 

Finally, in Table VI for incremental build, this time, the batches of different sizes (2^20, 2^21, 2^22) consisted of edges of the dataset itself (e.g., delauney, road, soc-LJ)  and not randomly generated, right? 

Thank you for the clarifications!

**Comment by maawad** [comment]
> @maawad Thank you for fixing the issue with allocate. It is working now. Thanks for your suggestions on performing batched insertion/deletion experiments. I have a lingering question on the experiment setup for Table II and Table III in the paper (I understand that Table IV is not reproducible because vertex deletion is not implemented here yet).

Vertex deletion is not too complicated. I have an issue for it https://github.com/gunrock/gunrock/issues/699, I'll try to work on it soon. 

> 
> For example, in Table II's (Table III's) experiments, let's say soc-LiveJournal1 was first entirely built in GPU memory and then a batch of a given size (2^16-2^22) of randomly generated edges were inserted (deleted) into the already-entirely-built soc-LiveJournal graph? Or is my understanding incorrect?
>

You are correct. For every batch size, all the different graphs were bulk built, then a batch of randomly generated edges with sources and destination between 0 : `num_vertices` (no uniqueness is guaranteed for these randomly generated edges) is inserted (or deleted). Each row in the table is the average throughput over all graphs for the specific batch size.  

> Finally, in Table VI for incremental build, this time, the batches of different sizes (2^20, 2^21, 2^22) consisted of edges of the dataset itself (e.g., delauney, road, soc-LJ) and not randomly generated, right?

Correct. The edges are already known for this experiment. The initial graph is loaded and inserted into an empty data structure using a given batch size. One note that we mention in Sec VI-B-2 is that our data structure, in this case, is just a linked list and not a hash table (since we don't know how many edges are going to be inserted, and each hash table becomes a single bucket).

> Thank you for the clarifications!

No worries. Happy to help!

I'm closing the issue, but feel free to reopen it (or open a new one) if you have more questions.
