### ISSUE TITLE
Standalone building the Gunrock SAGE example

### ISSUE THREAD

**Issue by YukeWang96** [gunrock/gunrock#873]
**Hi, All**

**How could I build the Grunrock SAGE example without building/testing other parts?**

It seems that when I follow the command
```
git clone --recursive https://github.com/gunrock/gunrock/
cd gunrock/example/sage
```

it gives me the error like.

```
../../gunrock/oprtr/oprtr_parameters.cuh:19:10: fatal error: moderngpu/context.hxx: No such file or directory
 #include <moderngpu/context.hxx>
```
Can anyone give me help with this problem? is there any way that I can manually link this library?

Thanks!

**Comment by jowens** [comment]
That looks like you've got the wrong versions/headers for moderngpu. @crozhon ? Can you help?

**Comment by crozhon** [comment]
Use CMake to build and you shouldn't encounter this. We updated our dependencies to be pulled via CPM instead of git submodules, and haven't updated the legacy Makefiles to alert the developer. 

```
mkdir build
cd build
cmake ..
# CPM: adding package ModernGPU@2.12
make sage
```

If you're really stubborn about not using CMake, the Makefile will work fine as long as moderngpu is cloned to externals/moderngpu, so you can also do:

```
cd externals 
git clone https://github.com/moderngpu
```

Once you have moderngpu the Makefiles should work as before.

**Comment by YukeWang96** [comment]
Hi, 

I have one more question if I want to use the sage outside its current directory (under example/sage). Instead of using CMake provided by Gunrock, I want to use `nvcc` with a set of flags for compilation, how could I achieve that? Since I want to use `sage` in another project outside the Gunrock directory.

Thanks!

**Comment by crozhon** [comment]
If you clone moderngpu to the externals directory, then you can use the Makefile in examples/sage to build.
