### ISSUE TITLE
Is current master branch broken?

### ISSUE THREAD

**Issue by fasiddique** [gunrock/gunrock#892]
I am trying to build gunrock following the instructions provided [here](https://gunrock.github.io/docs/#/?id=quick-start-guide). However, I am getting errors (screenshot attached) while running make. 
Here is the config I am using:
OS: Ubuntu 20.04.3 LTS
gcc: 8.4.0
nvcc: V10.1.243
GPU: NVIDIA Corporation GP107GL [Quadro P400]
![Screenshot from 2021-10-11 12-59-25](https://user-images.githubusercontent.com/43123425/136829589-15597de2-59c2-451a-9b88-7fb8008f04c1.png)

**Comment by crozhon** [comment]
I just built master on our cluster machine. 

I _think_ this error comes from an insufficient compiler version. Try updating to GCC version 9. The installation guide mentions that GCC9.3 is default for Ubuntu 20.04 (https://docs.nvidia.com/cuda/cuda-installation-guide-linux/), so that's probably what's wrong. Check if you already have gcc-9 installed, and set it as the default compiler:

```
# Check installed GCC versions
ls /usr/bin/gcc*
# /usr/bin/gcc 
# /usr/bin/gcc-9
# /usr/bin/gcc-8

rm -rf build
export CC=gcc-9
export CXX=g++-9
```
