### ISSUE TITLE
Delta-stepping in SSSP

### ISSUE THREAD

**Issue by AKKamath** [gunrock/gunrock#897]
The paper (https://arxiv.org/pdf/1501.05387.pdf) claims that SSSP implementation uses delta-stepping optimisation to reduce work load during execution.

I couldn't find the relevant code in the source (https://github.com/gunrock/gunrock/blob/fa530c7bbc54194dfd3e7097d595885184b1f4b3/gunrock/app/sssp/sssp_enactor.cuh) which performs this optimisation. I was wondering if it was indeed used, and if so, where the relevant code for its implementation was.

**Comment by jowens** [comment]
I'm pretty sure the current implementation does not do any delta-stepping. @yzhwang / @neoblizz might have a comment?

**Comment by jowens** [comment]
Kindly do note that the 2014 Davidson SSSP work (https://escholarship.org/uc/item/8qr166v2) advocated a near-far queue that was ~delta-stepping-ish (and discussed full delta-stepping).

**Comment by AKKamath** [comment]
I see. Thanks for the reply!

**Comment by yzhwang** [comment]
We have an approximated delta-stepping SSSP in v0.2 release of Gunrock and disabled it for v0.3+ releases. One possible reason was because since v0.3 we were introducing a unified interface of single and multi-GPU implementation. That means for our artifacts evaluation of PPoPP (which we used v0.3.1), there was no delta-stepping in SSSP.
Our two-rank near far pile priority queue implementation is here:
https://github.com/gunrock/gunrock/tree/v0.2/gunrock/priority_queue
And how it's used in SSSP in our v0.2 release:
https://github.com/gunrock/gunrock/blob/v0.2/gunrock/app/sssp/sssp_enactor.cuh#L381

Hope this helps.
